# Generated by Django 4.1 on 2023-04-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_contest_ending_date_contest_starting_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="kepcoin",
            field=models.IntegerField(default=0),
        ),
    ]
