# Generated by Django 4.1 on 2023-04-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_botuser_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemContestUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.IntegerField()),
                ("rating", models.IntegerField(default=0)),
                ("big_rating", models.IntegerField(default=0)),
                ("contests", models.IntegerField(default=0)),
                ("beginner", models.IntegerField(default=0)),
                ("basic", models.IntegerField(default=0)),
                ("normal", models.IntegerField(default=0)),
                ("medium", models.IntegerField(default=0)),
                ("advanced", models.IntegerField(default=0)),
                ("hard", models.IntegerField(default=0)),
            ],
        ),
    ]
