# Generated by Django 4.1 on 2023-04-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_variable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="example",
            field=models.TextField(null=True),
        ),
    ]
