# Generated by Django 4.1 on 2023-04-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_alter_problem_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="example",
            field=models.TextField(default=None),
        ),
    ]
