# Generated by Django 4.1 on 2023-04-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_alter_problem_example"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="example",
            field=models.TextField(blank=True, null=True),
        ),
    ]
