# Generated by Django 4.1 on 2023-04-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0016_solvedproblem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="incoming_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
