# Generated by Django 4.1 on 2023-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0017_alter_problem_incoming_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="problem_to_solve",
            field=models.IntegerField(null=True),
        ),
    ]
