# Generated by Django 4.1 on 2023-04-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0018_variable_problem_to_solve"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="incoming_data",
            new_name="incoming_data_ru",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="outgoing_data",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="title",
        ),
        migrations.AddField(
            model_name="problem",
            name="condition_ru",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="problem",
            name="condition_uz",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="problem",
            name="incoming_data_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="outgoing_data_ru",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="problem",
            name="outgoing_data_uz",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="problem",
            name="title_ru",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="problem",
            name="title_uz",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
