# Generated by Django 4.1 on 2023-04-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0019_rename_incoming_data_problem_incoming_data_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="outgoing_data_ru",
            field=models.TextField(default="Решение проблемы в одну строку"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="outgoing_data_uz",
            field=models.TextField(default="Yagona qatorda masala yechimi"),
        ),
    ]
