# Generated by Django 4.1 on 2023-04-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0020_alter_problem_outgoing_data_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("bgeginner", "⚪️"),
                    ("basic", "🟢"),
                    ("normal", "🔵"),
                    ("medium", "🟡"),
                    ("advanced", "🟠"),
                    ("hard", "🔴"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="outgoing_data_ru",
            field=models.TextField(default="Результат вычисления."),
        ),
    ]
