# Generated by Django 4.1 on 2023-04-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0021_alter_problem_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("⚪️", "bgeginner"),
                    ("🟢", "basic"),
                    ("🔵", "normal"),
                    ("🟡", "medium"),
                    ("🟠", "advanced"),
                    ("🔴", "hard"),
                ],
                max_length=255,
            ),
        ),
    ]
