# Generated by Django 4.1 on 2023-04-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0023_alter_problem_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("🟢", "beginner"),
                    ("🟡", "normal"),
                    ("🟠", "medium"),
                    ("🔴", "hard"),
                ],
                max_length=255,
            ),
        ),
    ]
