# Generated by Django 4.1 on 2023-04-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0025_userattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="userattempt",
            name="status",
            field=models.CharField(default="not_checked", max_length=255),
        ),
    ]
