# Generated by Django 4.1 on 2023-04-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0032_testcategory_test"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="answer",
            new_name="answer_uz",
        ),
        migrations.RemoveField(
            model_name="test",
            name="option1",
        ),
        migrations.RemoveField(
            model_name="test",
            name="option2",
        ),
        migrations.RemoveField(
            model_name="test",
            name="option3",
        ),
        migrations.RemoveField(
            model_name="test",
            name="question",
        ),
        migrations.AddField(
            model_name="test",
            name="answer_ru",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="test",
            name="option1_ru",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="test",
            name="option1_uz",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="test",
            name="option2_ru",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="test",
            name="option2_uz",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="test",
            name="option3_ru",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="test",
            name="option3_uz",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="test",
            name="question_ru",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="test",
            name="question_uz",
            field=models.TextField(default=""),
        ),
    ]
