# Generated by Django 4.1 on 2023-04-30 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0035_remove_testcategory_best_result_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="category",
        ),
        migrations.AddField(
            model_name="test",
            name="theme",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.testtheme",
            ),
        ),
    ]
