# Generated by Django 4.1 on 2023-05-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0037_remove_test_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="test_category",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="variable",
            name="test_theme",
            field=models.CharField(default="", max_length=255),
        ),
    ]
