# Generated by Django 4.1 on 2023-05-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0038_variable_test_category_variable_test_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="test_category",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="variable",
            name="test_theme",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
