# Generated by Django 4.1 on 2023-05-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0039_alter_variable_test_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="attempt_page",
            field=models.IntegerField(default=1),
        ),
    ]
