# Generated by Django 4.1 on 2023-05-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0040_variable_attempt_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="button",
            name="fucntion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
