# Generated by Django 4.1 on 2023-05-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0041_button_fucntion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solvedproblem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend.userattempt"
            ),
        ),
    ]
