# Generated by Django 4.1 on 2023-05-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0043_remove_solvedproblem_problem_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="solvedproblem",
            name="attempt",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.userattempt",
            ),
        ),
        migrations.AlterField(
            model_name="solvedproblem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend.botuser"
            ),
        ),
    ]
