# Generated by Django 4.1 on 2023-05-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0044_solvedproblem_attempt_alter_solvedproblem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solvedproblem",
            name="attempt",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.problem",
            ),
        ),
    ]
