# Generated by Django 4.1 on 2023-05-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0046_userattempt_solved_alter_solvedproblem_attempt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SolvedProblem",
        ),
    ]
