# Generated by Django 4.1 on 2023-04-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                ("fullname", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=10)),
                ("status", models.CharField(default="user", max_length=255)),
                ("new_user", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body_uz", models.TextField()),
                ("body_ru", models.TextField()),
            ],
        ),
    ]
