# Generated by Django 4.1 on 2023-04-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_botuser_kepcoin"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
